// This is automatically generated by the Tiger compiler.
// Do NOT modify!

// structures
struct Factorial
{
  struct Factorial_vtable *vptr;
};
struct Fac
{
  struct Fac_vtable *vptr;
};
struct Add
{
  struct Add_vtable *vptr;
  int a;
  int b;
  int sum;
};
// vtables structures
struct Factorial_vtable
{
};

struct Fac_vtable
{
  int (*ComputeFac)();
};

struct Add_vtable
{
  int (*result)();
};


// methods declare
int Fac_ComputeFac(struct Fac * this, int num);
int Add_result(struct Add * this);

// vtables
struct Factorial_vtable Factorial_vtable_ = 
{

};

struct Fac_vtable Fac_vtable_ = 
{
  Fac_ComputeFac
};

struct Add_vtable Add_vtable_ = 
{
  Add_result
};


// main method
int Tiger_main ()
{
  struct Fac * x_0;
  System_out_println ((x_0=((struct Fac*)(Tiger_new (&Fac_vtable_, sizeof(struct Fac)))), x_0->vptr->ComputeFac(x_0, 10)));
}


// methods
int Fac_ComputeFac(struct Fac * this, int num)
{
  int num_aux;
  struct Add * add;
  int addresult;
  struct Fac * x_1;
  struct Add * x_2;

  if (num < 1){
    num_aux = 1;
  }
  else
    num_aux = num * (x_1=this, x_1->vptr->ComputeFac(x_1, num - 1));
  add = ((struct Add*)(Tiger_new (&Add_vtable_, sizeof(struct Add))));
  addresult = (x_2=add, x_2->vptr->result(x_2));
  return addresult;
}
int Add_result(struct Add * this)
{
  int a;
  int b;
  int sum;

  a = 1;
  b = 2;
  sum = a + b;
  return sum;
}



